model:
  name: "google/gemma-3n-E2B-it"
  model_type: "gemma3n"
  trust_remote_code: true
  torch_dtype: "bfloat16"
  device_map: "auto"
  attn_implementation: "eager"
  
tokenizer:
  name: "google/gemma-3n-E2B-it"
  padding_side: "right"
  truncation_side: "right"
  add_eos_token: true
  add_bos_token: false
  
generation:
  max_new_tokens: 512
  temperature: 0.7
  top_p: 0.9
  top_k: 50
  do_sample: true
  repetition_penalty: 1.1
  pad_token_id: 0
  eos_token_id: 1
  
quantization:
  load_in_4bit: false
  load_in_8bit: false
  bnb_4bit_compute_dtype: "bfloat16"
  bnb_4bit_quant_type: "nf4"
  bnb_4bit_use_double_quant: true
